### ISSUE TITLE
Mediacode not working?

### ISSUE THREAD

**Issue by DocSneider** [achushu/CH57x-keyboard-mapper#2]
Hello,

firstly a big thanks for your work!

I have zero to nothing experience with go, but I tried my best to get a bit into it.

But I am not able to get the Mediacodes to work with my Macropad. 
It has 3 Keys + 1 Rotary-encoder, the µC is a **CH552g**. So far I somehow managed to set "normal" keys and things like CTRL+C. 

Bit if I Enter e.g  `{NOMOD, PLAY}` It seems not to overwrite the existing code for this key.

Am I doing something wrong? Or is there maybe a bug?

Thanks in advance :-)

**Comment by alfem** [comment]
Hi @DocSneider , I thinkI have got the same 3 keys+turn knob keypad. 
Did you change VENDOR_ID and PRODUCT_ID in hardware.go?

**Comment by theFox6** [comment]
It seems the Media Keys were not properly implemented yet.
Their binding data is way different from key macros, which can be seen in the comments within the existing code:
https://github.com/achushu/CH57x-keyboard-mapper/blob/3511c11303356bb8976220a86073e9e4cd173c32/keycodes.go#L180
You can test if my changes in #5 work.
